steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/ng'
    args: ['build', 'dashboard', '--sourceMap=true', '--statsJson']
  - name: 'gcr.io/$PROJECT_ID/ng'
    args: ['build', 'planner-form', '--sourceMap=true', '--statsJson']
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - deploy
      - --debug
      - --only=hosting:prod
